"""Add stripe_subscription_id to user_subscriptions

Revision ID: 0289c1ad2c1b
Revises: 0eadfc0b4839
Create Date: 2025-08-09 20:50:29.033658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0289c1ad2c1b'
down_revision = '0eadfc0b4839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_user_subscriptions_stripe_subscription_id', ['stripe_subscription_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_subscriptions_stripe_subscription_id', type_='unique')
        batch_op.drop_column('stripe_subscription_id')

    # ### end Alembic commands ###
